**Challenge - FIAP - 2026 - ClickBus**

Desafio 1 - SEGUIMENTAR
1. Decodificando o Comportamento do Cliente
- Perfil de compra
Objsetivo: Seguimentar os clientes em grupos distintos com base em seu histórico de compras
- foco em entender os diferentes perfis de viajantes
- possam ser tratados por Growth (promoções, e-mails, marketing, push)

PLUS: Construir um dashboard para monitorar o comportamento de compra dos grupos de clientes

Desafio 2 - PREVISÂO

2. timing é tudo
- Prever, para um conjunto de clientes se eles realizarão qualquer compra na plataforma dentro de uma janeala de tempo futura definida (próximos 7 ou 30 dias)
- classificação binária

PLUS: prever o número de dias até a próxima compra do cliente

Desafio 3 - PREVISÂO

3. Previsão do próximo trecho
- prever qual o trecho específico (par origem-destino) um cliente tem maior probabilidade de comprar em sua próxima viagem
- pode ser abordado como classificação multi-classe ou recomendação

Plus: combinar com o desafio 2, entregando a data e trecho da próxima compra

In [1]:
import pandas as pd
import gdown
import os

In [2]:
url_df = "https://drive.google.com/uc?id=1H43N5nTAWX7TdPIkX1G3nf50bxTw18JD"
out_df= "challenge.csv"

gdown.download(url_df, out_df, quiet=False)

Downloading...
From (original): https://drive.google.com/uc?id=1H43N5nTAWX7TdPIkX1G3nf50bxTw18JD
From (redirected): https://drive.google.com/uc?id=1H43N5nTAWX7TdPIkX1G3nf50bxTw18JD&confirm=t&uuid=d0fc7477-b542-4add-a833-51461ae0c992
To: /content/challenge.csv
100%|██████████| 660M/660M [00:10<00:00, 64.0MB/s]

'challenge.csv'

In [3]:
df_bronze = pd.read_csv('/content/challenge.csv', index_col = 0)
df_bronze.head()

,fk_contact,date_purchase,time_purchase,place_origin_departure,place_destination_departure,place_origin_return,place_destination_return,fk_departure_ota_bus_company,fk_return_ota_bus_company,gmv_success,total_tickets_quantity_success
nk_ota_localizer_id,,,,,,,,,,,
bc02d5245bec63b30ff1102fa273fc03f58bc9cc3f674ef1fee010c95dcbbab9,a7218ff4ee7d37d48d2b4391b955627cb089870b934912...,2018-12-26,15:33:35,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,50e9a8665b62c8d68bccc77c7c92431a1aa26ccbd38ed4...,0,0,8527a891e224136950ff32ca212b45bc93f69fbb801c3b...,1,89.09,1
5432f12612dd5d749b3be880e779989cf63b5efa4bcc4e76c53e661b07ed7fb8,37228485e0dc83d84d1bcd1bef3dc632301bf6cb22c8b5...,2018-12-05,15:07:57,10e4e7caf8b078429bb1c80b1a10118ac6f963eff098fd...,e6d41d208672a4e50b86d959f4a6254975e6fb9b088116...,0,0,36ebe205bcdfc499a25e6923f4450fa8d48196ceb4fa0c...,1,155.97,1
fb3caed9b2f1b6016d45ccddb19095476e61a2c85faa8ec869b8b02d6c729858,3467ec081e2421e72c96e7203b929d21927fd00b6b5f28...,2018-12-21,18:41:54,7688b6ef52555962d008fff894223582c484517cea7da4...,8c1f1046219ddd216a023f792356ddf127fce372a72ec9...,0,0,ec2e990b934dde55cb87300629cedfc21b15cd28bbcf77...,1,121.99,1
4dc44a6dd592b702feccb493d192210c86965aee68452989fa44926bd8e0a421,ab3251a2be0f69713b8f97b0e9d1579e31551f4fd4facf...,2018-12-06,14:01:38,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,d6acb3c1a79e57bcc03d976cb4d98f56edccd4cf426392...,0,0,5f9c4ab08cac7457e9111a30e4664920607ea2c115a143...,1,55.22,1
aa34ed7fd0a6b405df2df1bf9f8d68e6df9b9a868a6181f2a990463e6eec11d3,ceea0de820a6379f2c4215bddaec66c33994b304607e56...,2021-02-23,20:08:25,7688b6ef52555962d008fff894223582c484517cea7da4...,23765fc69c4e3c0b10f5d15471dc2245e2a19af16b513f...,0,0,48449a14a4ff7d79bb7a1b6f3d488eba397c36ef25634c...,1,45.31,1

In [4]:
df_bronze.shape

(1741344, 11)

In [5]:
df_bronze.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1741344 entries, bc02d5245bec63b30ff1102fa273fc03f58bc9cc3f674ef1fee010c95dcbbab9 to 113a96cafbc0fc70ab6cfba8bc017c57e720366265820c128b3ecc23f846a628
Data columns (total 11 columns):
 #   Column                          Dtype
---  ------                          -----
 0   fk_contact                      object
 1   date_purchase                   object
 2   time_purchase                   object
 3   place_origin_departure          object
 4   place_destination_departure     object
 5   place_origin_return             object
 6   place_destination_return        object
 7   fk_departure_ota_bus_company    object
 8   fk_return_ota_bus_company       object
 9   gmv_success                     float64
 10  total_tickets_quantity_success  int64
dtypes: float64(1), int64(1), object(9)
memory usage: 159.4+ MB

In [6]:
df_bronze.isnull().sum()

fk_contact                        0
date_purchase                     0
time_purchase                     0
place_origin_departure            0
place_destination_departure       0
place_origin_return               0
place_destination_return          0
fk_departure_ota_bus_company      0
fk_return_ota_bus_company         0
gmv_success                       0
total_tickets_quantity_success    0
dtype: int64

In [11]:
df_bronze.duplicated().sum()

np.int64(3)

In [8]:
inicial_date = df_bronze['date_purchase'].min()
final_date = df_bronze['date_purchase'].max()

print(f"Data Inicial dos Dados: {inicial_date}")
print(f"Data Final dos Dados: {final_date}")

Data Inicial dos Dados: 2013-09-12
Data Final dos Dados: 2024-04-01

In [10]:
# --- Data Profiling ---
print("--- Check de Integridade Bronze ---")
print(f"Shape: {df_bronze.shape}")
print(f"Período: {df_bronze['date_purchase'].min()} até {df_bronze['date_purchase'].max()}")

print(f"Duplicatas: {df_bronze.duplicated().sum()}")
print("-" * 30)
# Nota: duplicatas são mantidas na camada Bronze (dado fiel à origem).
# Remoção será feita na camada Prata.

print(f"Tipos de Dados:\n{df_bronze.dtypes}")
print("-" * 30)

df_bronze.to_parquet('clickbus_bronze.parquet', index=False)
print("Bronze salvo com sucesso em formato Parquet (Tipagem preservada).")

--- Check de Integridade Bronze ---
Shape: (1741344, 11)
Período: 2013-09-12 até 2024-04-01
Duplicatas: 3
------------------------------
Tipos de Dados:
fk_contact                         object
date_purchase                      object
time_purchase                      object
place_origin_departure             object
place_destination_departure        object
place_origin_return                object
place_destination_return           object
fk_departure_ota_bus_company       object
fk_return_ota_bus_company          object
gmv_success                       float64
total_tickets_quantity_success      int64
dtype: object
------------------------------
Bronze salvo com sucesso em formato Parquet (Tipagem preservada).